version: '2'

services:
    shell:
        restart: always
        image: elixir:1.2
        volumes:
            - .:/code
        working_dir: "/code"
        container_name: elixir_study
        command: "/bin/bash"
    iex:
        extends:
            service: shell
        command: "iex"
